### ISSUE TITLE
PLDI 2021 할일 (deadline: 2020년 11월 중순)

### ISSUE THREAD

**Issue by kyeongmincho** [kaist-cp/view-hw#54]
## Promising TSO

- [x] Axiomatic 정의
- [x] Promising 정의
- [x] AtoP
- [x] PtoPF
- [x] PFtoA
  - rmw 관련한 sim_th PROP들 수정
  - external, corw, cowr
- [x] PFtoV(#46)
- [x] VtoP

## Promising ARM for Persistency

- [x] Axiomatic 정의
- [x] Promising 정의
- [x] AtoP
- [x] PtoPF
- [x] PFtoA

## Promising TSO for Persistency

- [ ] `[W];po;[FO];po;[SF]` 같은 식으로 실행했을 때 persist가 되지 않는 행동이 일어나는지 실험방법 강구 및 실험 (#34)
- [x] Axiomatic 정의 (pob)
- [x] Promising 정의 (persistency view)
- [x] AtoP (pob)
- [x] PtoPF (pob)
- [x] PFtoA (pob)
- [x] PFtoV (pob)
- [x] VtoP (pob)
- [x] Axiomatic dom 정의
- [x] AtoP (dom ~ global per view)
- [x] PtoPF (global per view)
- [x] PFtoA (dom ~ global per view)
- [x] PFtoV (global per view)
- [x] VtoP (global per view)

## 증명 끝났는데 시간이 남는다면

- [x] 캐시라인 추가(#63)
- [x] ARM internal 단순화 (#23)
- [ ] ARM/TSO 코드 통합 리팩토링

## persistent library?

- [ ] (빅터논문에서는) MSQ?

## Model Checker

- [ ] 구현
- [ ] 벤치마크

## 논문 작성
- [x] Coq과의 불일치 고치기
- [ ] README 정리
